# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7bf06cf7a90082e94163267f83fd38250acc7f6b71b3eb55f21a0cec88760c1daf73011cbee4fe926d022f2b8a297d44a4075e51bdbf81f5adb1552eb25acbb

test:
  secret_key_base: 66d75b4756ea0257d635506020d572e565a6318b2eee59726a477d9224a84b192d158388a11849ec91cb7c01ed575b7a077137dfe34d2f492dd6f96a9682b275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
